version: '3'
services:
  agent:
    build:
      context: .      
      args:
        - mode=train
    volumes:
      - agentmodel:/model
    image: kulhanek/visual-navigation-agent-pytorch

  train:
    command: "train.py"
    image: kulhanek/visual-navigation-agent-pytorch

volumes:
  agentmodel: